#!/usr/bin/env python3
"""报告生成器 — 生成结构化的审查报告"""

import json
import sys
from pathlib import Path
from datetime import datetime


TEMPLATES = {
    "markdown": """\
# Code Quality Report

**File:** {file}
**Language:** {language}
**Score:** {score}/100 ({grade})
**Gate:** {gate}
**Date:** {date}

---

## Axis Breakdown

| Axis | Score | Max | % | Deductions |
|------|-------|-----|---|------------|
{axes_table}

---

## Details

### Correctness ({correctness_score}/20)
{correctness_details}

### Readability ({readability_score}/20)
{readability_details}

### Architecture ({architecture_score}/25)
{architecture_details}

### Security ({security_score}/20)
{security_details}

### Performance ({performance_score}/15)
{performance_details}

---

## Recommendations
{recommendations}

---
*Generated by Code Quality Guard v3.0*
""",
}


def generate_report(result: dict, format: str = "markdown") -> str:
    """生成审查报告"""
    axes = result.get("axes", {})

    axes_table = ""
    for axis_name, axis_data in axes.items():
        score = axis_data.get("score", 0)
        max_s = axis_data.get("max", 20)
        pct = axis_data.get("percentage", 0)
        ded = "; ".join(axis_data.get("deductions", [])) or "-"
        axes_table += f"| {axis_name.capitalize()} | {score} | {max_s} | {pct}% | {ded} |\n"

    recommendations = []
    if result["gate"] == "reject":
        recommendations.append("⚠️ **REJECTED**: Must rewrite and re-review")
    elif result["gate"] == "needs-fix":
        recommendations.append("⚠️ **Conditional Pass**: Fix critical issues before merge")
    elif result["gate"] == "conditional-pass":
        recommendations.append("✅ **Conditional Pass**: Fix warnings before merge")

    for axis_name, axis_data in axes.items():
        for d in axis_data.get("deductions", []):
            recommendations.append(f"- [{axis_name}] {d}")

    if result.get("distillation_candidate"):
        recommendations.append("✨ **Distillation Candidate**: Score ≥ 90, qualifies for pattern library")

    return TEMPLATES["markdown"].format(
        file=result.get("file", "unknown"),
        language=result.get("language", "unknown").upper(),
        score=result.get("composite_score", 0),
        grade=result.get("grade", "Unknown"),
        gate=result.get("gate", "unknown"),
        date=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        axes_table=axes_table,
        correctness_score=axes.get("correctness", {}).get("score", 0),
        correctness_details="<br>".join(axes.get("correctness", {}).get("deductions", ["No issues"]) or ["-"]),
        readability_score=axes.get("readability", {}).get("score", 0),
        readability_details="<br>".join(axes.get("readability", {}).get("deductions", ["No issues"]) or ["-"]),
        architecture_score=axes.get("architecture", {}).get("score", 0),
        architecture_details="<br>".join(axes.get("architecture", {}).get("deductions", ["No issues"]) or ["-"]),
        security_score=axes.get("security", {}).get("score", 0),
        security_details="<br>".join(axes.get("security", {}).get("deductions", ["No issues"]) or ["-"]),
        performance_score=axes.get("performance", {}).get("score", 0),
        performance_details="<br>".join(axes.get("performance", {}).get("deductions", ["No issues"]) or ["-"]),
        recommendations="\n".join(f"- {r}" for r in recommendations) or "- No recommendations",
    )


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="JSON file or stdin")
    parser.add_argument("--format", "-f", default="markdown", choices=["markdown", "json"])
    parser.add_argument("--output", "-o", help="Output file")
    args = parser.parse_args()

    if args.input == "-":
        data = json.load(sys.stdin)
    else:
        with open(args.input) as f:
            data = json.load(f)

    if args.format == "markdown":
        report = generate_report(data)
    else:
        report = json.dumps(data, indent=2, ensure_ascii=False)

    if args.output:
        Path(args.output).write_text(report)
        print(f"Report written to {args.output}", file=sys.stderr)
    else:
        print(report)


if __name__ == "__main__":
    main()
